### ISSUE TITLE
Error in guide page for 'Creating a dynamic view with ejs'

### ISSUE THREAD

**Issue by twgardner2** [alarner/react-express-template#101]
I apologize if this is the wrong place to bring this up, but I think there is a small error in the perk guide. The final example on the 'Creating a dynamic view with ejs' page, shows the escaped ejs tag where I think it should show the unescaped ejs tag:
![perk error](https://user-images.githubusercontent.com/26434599/39854753-6725b236-5429-11e8-88c8-8fe0f84b46a6.png)

**Comment by alarner** [comment]
Hey @twgardner2 thanks for the bug report. I've got this on my todo list now, but might not fix for a few weeks because I've got a ton of other work. If you want to submit a PR this is where you can find that doc page: https://github.com/alarner/perk-docs/blob/master/src/v1/guides/creating-a-dynamic-view-with-ejs.md

Cheers!

**Comment by twgardner2** [comment]
Great - I was having trouble finding that page of the docs. Single
character PR submitted!

**Comment by alarner** [comment]
@twgardner2 merged and deployed! Thanks for the PR.
